name: Trigger auto deployment for myacatest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myacatest-AutoDeployTrigger-b6f5432d-9c85-410e-b60f-0d71f5400897.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYACATEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYACATEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYACATEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.MYACATEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYACATEST_REGISTRY_PASSWORD }}
          containerAppName: myacatest
          resourceGroup: myacatest
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


